name: Mastodon Bot Scheduled Posting

on:
  schedule:
    - cron: '0 1 * * *'    # UTC 01:00 = 北京时间 09:00
    - cron: '0 13 * * *'   # UTC 13:00 = 北京时间 21:00

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install requests
        run: pip install requests

      - name: Run bot script
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          INSTANCE_URL: ${{ secrets.INSTANCE_URL }}
        run: python bot.py